In [40]:
import tensorflow as tf
print(tf.__version__)

2.0.0-rc0


In [3]:
print(tf.test.is_gpu_available())

False


## 张量

In [10]:
x1=tf.Variable("elephant",tf.string)

In [9]:
print(x1)
tf.print(x1)

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'elephant'>
elephant


In [11]:
tf.print(tf.rank(x1))

0


In [12]:
tf.print(tf.shape(x1))

[]


In [13]:
x2=tf.Variable(["elephant"],tf.string)
tf.print(tf.rank(x2))
tf.print(tf.shape(x2))

1
[1]


In [18]:
x2=tf.Variable([["elephant","Kangaroo",'lion'],['chick','duck','goose']],tf.string)
tf.print(tf.rank(x2))
tf.print(tf.shape(x2))
tf.print(x2)

2
[2 3]
[["elephant" "Kangaroo" "lion"]
 ["chick" "duck" "goose"]]


### 常数张量

In [20]:
tf.constant([1,2,3],dtype=tf.int16)

<tf.Tensor: id=122, shape=(3,), dtype=int16, numpy=array([1, 2, 3], dtype=int16)>

In [21]:
tf.zeros((2,2),dtype=tf.int16)

<tf.Tensor: id=125, shape=(2, 2), dtype=int16, numpy=
array([[0, 0],
       [0, 0]], dtype=int16)>

In [24]:
rank_three_tensor=tf.ones([3,4,5])
new_matrix=tf.reshape(rank_three_tensor,[6,10])
tf.print(new_matrix)

[[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]]


## 操作

### tf.strings

In [27]:
tf.strings.bytes_split('hello world')

<tf.Tensor: id=256, shape=(11,), dtype=string, numpy=
array([b'h', b'e', b'l', b'l', b'o', b' ', b'w', b'o', b'r', b'l', b'd'],
      dtype=object)>

In [25]:
tf.strings.split('hello world')

<tf.Tensor: id=195, shape=(2,), dtype=string, numpy=array([b'hello', b'world'], dtype=object)>

In [26]:
tf.strings.to_hash_bucket(['hello','world'],num_buckets=100)

<tf.Tensor: id=197, shape=(2,), dtype=int64, numpy=array([38, 61], dtype=int64)>

### tf.debugging:用于debugs,使用机会少

In [28]:
a=tf.random.uniform((10,10))

In [29]:
tf.debugging.assert_equal(x=a.shape,y=(10,10))

In [ ]:
tf.debugging.assert_equal(x=a.shape,y=(10,20))

### tf.random

In [32]:
a=tf.random.uniform((10,10))
tf.print(a)

[[0.374935985 0.624134779 0.581524134 ... 0.0494647026 0.21299696 0.591108918]
 [0.554579139 0.800860286 0.605820775 ... 0.22553277 0.992053151 0.931208491]
 [0.412311912 0.690237403 0.835447192 ... 0.29886198 0.373683929 0.910890102]
 ...
 [0.813340545 0.279341459 0.810765386 ... 0.123179317 0.827406883 0.359028578]
 [0.0765993595 0.586132526 0.281611204 ... 0.390592575 0.332724929 0.166840672]
 [0.266418815 0.841287374 0.79472971 ... 0.658883 0.970568657 0.722027898]]


In [33]:
a=tf.random.uniform((10,10),minval=0,maxval=10)
tf.print(a)

[[7.98716545 7.96341515 9.39956856 ... 6.33747196 6.62571049 5.8694849]
 [9.85577488 4.00911236 2.78105974 ... 2.508564 0.630371571 7.77936935]
 [2.61495113 0.0721681118 9.10708618 ... 6.59230471 2.2546041 7.8329587]
 ...
 [3.24115396 0.532734394 2.71878123 ... 0.53666234 7.25714779 6.77472687]
 [1.84201 2.5020504 8.91274071 ... 9.92867851 6.75694704 6.30240917]
 [0.329127312 9.29658508 0.168277025 ... 4.98021841 9.23769951 9.95047665]]


### tf.math

In [35]:
a=tf.constant([[1,2],[3,4]])
b=tf.constant([[8,9],[6,7]])

tf.print(tf.math.add(a,b))
tf.print(tf.math.subtract(a,b))
tf.print(tf.math.multiply(a,b))
tf.print(tf.math.divide(a,b))

[[9 11]
 [9 11]]
[[-7 -7]
 [-3 -3]]
[[8 18]
 [18 28]]
[[0.125 0.22222222222222221]
 [0.5 0.5714285714285714]]


### tf.dtypes

In [37]:
x=tf.constant([1.8,2],dtype=tf.float32)

x1=tf.dtypes.cast(x,tf.int32)
x1

<tf.Tensor: id=366, shape=(2,), dtype=int32, numpy=array([1, 2])>

## 常用层
    - tf.keras.layers:基于tf.nn的高度封装
    - tf.nn

In [44]:
# 文本分类
a=tf.random.uniform(shape=(10,100,50),minval=-0.5,maxval=0.5) #张量
x1=tf.keras.layers.LSTM(100)(a) # LSTM
x2=tf.keras.layers.Dense(10)(x1) # 全连接层
x3=tf.nn.softmax(x2) #激活函数

# tf.print(a)
# print(x1)
# print(x2)
# print(x3)


# 三种建模方式
    - 顺序（Sequential）
    - 函数(Functional),推荐使用，可以更好理解神经网络
    - 子类化(Subclassing)

In [53]:
### tf.keras.Sequential
from tensorflow.keras import layers
import tensorflow as tf

model=tf.keras.Sequential()
model.add(layers.Dense(64,activation='relu',input_shape=(32,)))#第一层
model.add(layers.Dense(64,activation='relu'))#第二层
model.add(layers.Dense(10))#第三层


In [54]:
model.compile(optimizer=tf.keras.optimizers.Adam(0.01),
                loss=tf.keras.losses.CategoricalCrossentropy(from_logits=True),
             metrics=['accuracy'])

In [62]:
import numpy as np

data=np.random.random((1000,32))
labels=np.random.random((1000,10))

model.fit(data,labels,epochs=10,batch_size=12)

Train on 1000 samples
Epoch 1/10
1000/1000 [==============================] - 0s 180us/sample - loss: 253703.5762 - accuracy: 0.1110
Epoch 2/10
1000/1000 [==============================] - 0s 232us/sample - loss: 256421.8115 - accuracy: 0.1090
Epoch 3/10
1000/1000 [==============================] - 0s 212us/sample - loss: 325821.2849 - accuracy: 0.0850
Epoch 4/10
1000/1000 [==============================] - 0s 235us/sample - loss: 327319.2104 - accuracy: 0.0980
Epoch 5/10
1000/1000 [==============================] - 0s 215us/sample - loss: 435901.7737 - accuracy: 0.0950
Epoch 6/10
1000/1000 [==============================] - 0s 211us/sample - loss: 494963.8838 - accuracy: 0.1170
Epoch 7/10
1000/1000 [==============================] - 0s 226us/sample - loss: 565023.1934 - accuracy: 0.1090
Epoch 8/10
1000/1000 [==============================] - 0s 217us/sample - loss: 498747.8983 - accuracy: 0.1040
Epoch 9/10
1000/1000 [==============================] - 0s 202us/sample - loss: 614800.456

In [58]:
### Function Model
from tensorflow.keras import layers
import tensorflow as tf

inputs=tf.keras.Input(shape=(32,))
x=layers.Dense(64,activation='relu')(inputs) #第1层
x=layers.Dense(64,activation='relu')(x) #第2层
prediction=layers.Dense(10)(x)#第3层

model=tf.keras.Model(inputs=inputs,outputs=prediction)

model.compile(optimizer=tf.keras.optimizers.Adam(0.01),
                loss=tf.keras.losses.CategoricalCrossentropy(from_logits=True),
             metrics=['accuracy'])

In [60]:
import numpy as np

data=np.random.random((1000,32))
labels=np.random.random((1000,10))

model.fit(data,labels,epochs=10,batch_size=12)

Train on 1000 samples
Epoch 1/10
1000/1000 [==============================] - 1s 842us/sample - loss: 308.5965 - accuracy: 0.0770
Epoch 2/10
1000/1000 [==============================] - 0s 154us/sample - loss: 3369.5314 - accuracy: 0.0870
Epoch 3/10
1000/1000 [==============================] - 0s 170us/sample - loss: 12180.1277 - accuracy: 0.1160
Epoch 4/10
1000/1000 [==============================] - 0s 187us/sample - loss: 24497.9179 - accuracy: 0.1140
Epoch 5/10
1000/1000 [==============================] - 0s 204us/sample - loss: 46492.6850 - accuracy: 0.1000
Epoch 6/10
1000/1000 [==============================] - 0s 194us/sample - loss: 66967.7405 - accuracy: 0.0960
Epoch 7/10
1000/1000 [==============================] - 0s 155us/sample - loss: 89815.3757 - accuracy: 0.0830
Epoch 8/10
1000/1000 [==============================] - 0s 190us/sample - loss: 159080.3002 - accuracy: 0.0790
Epoch 9/10
1000/1000 [==============================] - 0s 199us/sample - loss: 149747.7629 - accura

# 子类模型：Subclassing Model，定义自己的前向传播模型来构建完全可定制的模型
### 主要用于科研，调包侠一般不会使用